#### baseline+M1+M2 4*4

In [1]:
from ultralytics import YOLO

model = YOLO("yaml/baseline+M1+M2.yaml")
model.info()  # 打印模型结构

WARNING ⚠️ no model scale passed. Assuming scale='n'.
baseline+M1+M2 summary: 177 layers, 3,004,210 parameters, 3,004,194 gradients, 9.3 GFLOPs

(177, 3004210, 3004194, 9.3456384)

In [3]:
from ultralytics import YOLO

# 加载模型
model = YOLO("yaml/baseline+M1+M2.yaml")

# 训练
results = model.train(
    data='neu-det.yaml',
    epochs=200,                # 训练200轮
    imgsz=200,                 # 图片大小200×200
    batch=16,                  # batch size 16
    name='baseline+M1+M2(16)',
    device=0,                 
    
    # 优化器设置
    optimizer='SGD',
    lr0=0.01,                  # 初始学习率0.01
    momentum=0.937,            # SGD动量
    weight_decay=0.0005,       # 权重衰减
    warmup_epochs=3,           # 3轮预热
    warmup_momentum=0.8,       # 预热阶段动量
    
    # 数据增强
    mosaic=1.0,                # Mosaic概率1.0
    copy_paste=0.0,
    mixup=0.0,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,
    degrees=0.0,
    translate=0.1,             # 平移比例0.1
    scale=0.5,                 # 缩放范围0.5
    shear=0.0,
    perspective=0.0,
    flipud=0.0,
    fliplr=0.5,                # 水平翻转概率0.5
    erasing=0.4,               # RandomErasing概率0.4
    augment=True,              # 开启RandAugment
    
    # 训练稳定性配置
    amp=True,
    cache=True,                # 开启缓存加速
    workers=8,                 # 数据加载线程数
    patience=50,               # 早停
    save=True,
    plots=True
)
# 1. 输出参数量 & GFLOPs
model_info = model.info()  # 会自动打印 params, GFLOPs

WARNING ⚠️ no model scale passed. Assuming scale='n'.
New https://pypi.org/project/ultralytics/8.4.46 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.4.43 🚀 Python-3.12.3 torch-2.7.0+cu128 CUDA:0 (NVIDIA GeForce RTX 4090, 48508MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=True, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=True, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=neu-det.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=200, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=200, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yaml/baseline+M1+M2.yaml, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=baseline+M1+M2(16), nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=50, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/root/runs/detect/baseline+M1+M2(16), save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
WARNING ⚠️ no model scale passed. Assuming scale='n'.

                   from  n    params  module                                       arguments
  0                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  1                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  2                  -1  1      5712  ultralytics.nn.modules.block.C3k2            [3, 64, 1, False, 0.25]
  3                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  8                  -1  1    313344  ultralytics.nn.modules.block.C3k2            [128, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1    262144  ultralytics.nn.modules.block.MDLA            [256, 256, 1]
 12                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 13             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 14                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 15                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 16             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 17                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 18                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
 19            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 20                  -1  1    119488  ultralytics.nn.modules.block.C3k2            [448, 128, 1, False]
 21                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
 22            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 23                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 24        [16, 19, 22]  1   1253794  ultralytics.nn.modules.head.Detect           [6, 16, None, [256, 448, 384]]
baseline+M1+M2 summary: 177 layers, 3,004,210 parameters, 3,004,194 gradients, 9.3 GFLOPs

Freezing layer 'model.24.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
WARNING ⚠️ imgsz=[200] must be multiple of max stride 32, updating to [224]
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 896.2±401.2 MB/s, size: 19.0 KB)
train: Scanning /root/NEU-DET/labels/train... 1440 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1440/1440 1.5Kit/s 1.0s0.1s
train: /root/NEU-DET/images/train/inclusion_62.jpg: 1 duplicate labels removed
train: /root/NEU-DET/images/train/patches_198.jpg: 1 duplicate labels removed
train: New cache created: /root/NEU-DET/labels/train.cache
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
train: Caching images (0.2GB RAM): 100% ━━━━━━━━━━━━ 1440/1440 5.5Kit/s 0.3s0.1s
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 559.1±349.8 MB/s, size: 14.4 KB)
val: Scanning /root/NEU-DET/labels/val... 180 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 180/180 1.4Kit/s 0.1s<0.1s
val: New cache created: /root/NEU-DET/labels/val.cache
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
val: Caching images (0.0GB RAM): 100% ━━━━━━━━━━━━ 180/180 3.2Kit/s 0.1s
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 74 weight(decay=0.0), 83 weight(decay=0.0005), 80 bias(decay=0.0)
Plotting labels to /root/runs/detect/baseline+M1+M2(16)/labels.jpg...
Image sizes 224 train, 224 val
Using 8 dataloader workers
Logging results to /root/runs/detect/baseline+M1+M2(16)
Starting training for 200 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/200     0.475G      4.463      3.893      3.746        112        224: 100% ━━━━━━━━━━━━ 90/90 9.7it/s 9.2s<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.2it/s 0.6s0.1s
                   all        180        724    0.00111      0.153    0.00184   0.000953

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/200     0.504G      3.965      3.114      3.132         98        224: 100% ━━━━━━━━━━━━ 90/90 11.6it/s 7.8s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.7it/s 0.6s.1s
                   all        180        724     0.0235       0.19     0.0294    0.00596

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/200     0.508G      3.547      2.994      2.876        149        224: 100% ━━━━━━━━━━━━ 90/90 11.4it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.9it/s 0.5s.3s
                   all        180        724     0.0365     0.0794     0.0226    0.00594

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/200     0.508G      3.166      2.759      2.646         90        224: 100% ━━━━━━━━━━━━ 90/90 13.8it/s 6.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 13.2it/s 0.5s.3s
                   all        180        724      0.431     0.0739     0.0521     0.0169

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/200     0.508G      2.961      2.602      2.498         85        224: 100% ━━━━━━━━━━━━ 90/90 14.7it/s 6.1s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.7it/s 0.5s.1s
                   all        180        724      0.514      0.183       0.17     0.0561

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/200     0.508G       2.76      2.436      2.342        142        224: 100% ━━━━━━━━━━━━ 90/90 12.8it/s 7.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.1it/s 0.5s.1s
                   all        180        724      0.672      0.169      0.174     0.0493

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/200     0.512G      2.591      2.271      2.209        118        224: 100% ━━━━━━━━━━━━ 90/90 11.6it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.9it/s 0.5s.1s
                   all        180        724      0.505      0.238       0.23     0.0827

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/200     0.512G      2.464      2.184      2.136        112        224: 100% ━━━━━━━━━━━━ 90/90 11.3it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.7it/s 0.5s.1s
                   all        180        724      0.295      0.344      0.271     0.0908

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/200     0.512G      2.365      2.126      2.092        148        224: 100% ━━━━━━━━━━━━ 90/90 11.5it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.9it/s 0.5s.1s
                   all        180        724      0.541      0.245       0.22     0.0702

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/200     0.512G      2.285      2.079       2.02        140        224: 100% ━━━━━━━━━━━━ 90/90 11.2it/s 8.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.1it/s 0.5s.1s
                   all        180        724       0.48      0.324      0.332      0.124

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/200     0.521G      2.221      2.023      1.995         98        224: 100% ━━━━━━━━━━━━ 90/90 11.6it/s 7.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.7it/s 0.5s.1s
                   all        180        724      0.547      0.333      0.303       0.12

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/200     0.521G      2.178      1.997      1.949        123        224: 100% ━━━━━━━━━━━━ 90/90 11.3it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.6it/s 0.5s.1s
                   all        180        724      0.409      0.352      0.341      0.134

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/200     0.521G      2.119      1.946      1.906         67        224: 100% ━━━━━━━━━━━━ 90/90 11.5it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.7it/s 0.5s.1s
                   all        180        724      0.314      0.516      0.381      0.151

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/200     0.521G      2.083      1.921      1.892        107        224: 100% ━━━━━━━━━━━━ 90/90 11.2it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.7it/s 0.5s.1s
                   all        180        724      0.335      0.402      0.381      0.155

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/200     0.521G      2.046      1.871      1.846        134        224: 100% ━━━━━━━━━━━━ 90/90 11.3it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.7it/s 0.5s.1s
                   all        180        724      0.536      0.361      0.377      0.163

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/200     0.521G      2.014      1.835      1.837         94        224: 100% ━━━━━━━━━━━━ 90/90 11.4it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.3it/s 0.5s.1s
                   all        180        724      0.444      0.423      0.402      0.171

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/200     0.521G      2.003      1.807      1.815        122        224: 100% ━━━━━━━━━━━━ 90/90 11.5it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 13.0it/s 0.5s.1s
                   all        180        724      0.529      0.425      0.488      0.214

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/200     0.521G      1.961      1.793      1.785         90        224: 100% ━━━━━━━━━━━━ 90/90 11.5it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.5it/s 0.5s.1s
                   all        180        724      0.415        0.4      0.404      0.172

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/200     0.521G      1.945      1.782      1.779         88        224: 100% ━━━━━━━━━━━━ 90/90 11.5it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.4it/s 0.5s.1s
                   all        180        724      0.481       0.48      0.487      0.217

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/200     0.521G      1.928      1.773      1.774         92        224: 100% ━━━━━━━━━━━━ 90/90 11.7it/s 7.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.5it/s 0.5s.1s
                   all        180        724        0.5      0.464      0.471      0.214

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/200     0.521G        1.9      1.728      1.733        146        224: 100% ━━━━━━━━━━━━ 90/90 11.8it/s 7.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.1it/s 0.5s.1s
                   all        180        724      0.395      0.553      0.455        0.2

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/200     0.533G      1.895      1.721      1.742        100        224: 100% ━━━━━━━━━━━━ 90/90 11.5it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.6it/s 0.5s.1s
                   all        180        724      0.477      0.524      0.506       0.22

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/200     0.533G      1.889      1.706      1.729        127        224: 100% ━━━━━━━━━━━━ 90/90 11.5it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.6it/s 0.5s.1s
                   all        180        724      0.711       0.39      0.482        0.2

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/200     0.533G      1.868      1.691      1.711        144        224: 100% ━━━━━━━━━━━━ 90/90 11.5it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.9it/s 0.5s.1s
                   all        180        724      0.436      0.498       0.48      0.222

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/200     0.533G      1.859      1.689      1.716        118        224: 100% ━━━━━━━━━━━━ 90/90 11.6it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.1it/s 0.5s.3s
                   all        180        724       0.46      0.556      0.516      0.236

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/200     0.533G       1.85      1.689      1.708        134        224: 100% ━━━━━━━━━━━━ 90/90 11.5it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.6it/s 0.5s.1s
                   all        180        724      0.458      0.517      0.516      0.231

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/200     0.533G      1.814      1.635      1.677         99        224: 100% ━━━━━━━━━━━━ 90/90 11.5it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.8it/s 0.5s.1s
                   all        180        724      0.435        0.5      0.493      0.218

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/200     0.533G      1.799      1.635      1.669        161        224: 100% ━━━━━━━━━━━━ 90/90 11.6it/s 7.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.6it/s 0.5s.1s
                   all        180        724      0.572      0.501      0.531      0.238

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/200     0.533G      1.793      1.636      1.666        135        224: 100% ━━━━━━━━━━━━ 90/90 11.6it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.6it/s 0.5s.1s
                   all        180        724      0.445      0.555       0.52      0.228

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/200     0.533G      1.785      1.625      1.665        119        224: 100% ━━━━━━━━━━━━ 90/90 11.7it/s 7.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 13.1it/s 0.5s.1s
                   all        180        724      0.486      0.537      0.533      0.237

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/200     0.533G      1.774      1.604       1.65        103        224: 100% ━━━━━━━━━━━━ 90/90 11.7it/s 7.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 13.1it/s 0.5s.1s
                   all        180        724      0.504      0.591      0.573      0.259

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/200     0.533G      1.791      1.614      1.666        135        224: 100% ━━━━━━━━━━━━ 90/90 11.7it/s 7.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.8it/s 0.5s.1s
                   all        180        724      0.546      0.539      0.553       0.25

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/200     0.533G      1.763      1.582      1.647        107        224: 100% ━━━━━━━━━━━━ 90/90 11.2it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.9it/s 0.5s.1s

In [4]:
model = YOLO('runs/detect/baseline+M1+M2(16)/weights/best.pt')
# 评估模型
metrics = model.val(
    data='neu-det.yaml',
    imgsz=200
)

# 打印评估指标
print(f"mAP50: {metrics.box.map50:.3f}")
print(f"mAP50-95: {metrics.box.map:.3f}")

WARNING ⚠️ imgsz=[200] must be multiple of max stride 32, updating to [224]
Ultralytics 8.4.43 🚀 Python-3.12.3 torch-2.7.0+cu128 CUDA:0 (NVIDIA GeForce RTX 4090, 48508MiB)
baseline+M1+M2 summary (fused): 103 layers, 2,994,842 parameters, 0 gradients, 9.2 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 973.2±166.5 MB/s, size: 19.2 KB)
val: Scanning /root/NEU-DET/labels/val.cache... 180 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 180/180 58.1Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 4.4it/s 2.7s0.3s
                   all        180        724      0.729      0.707      0.742      0.395
               crazing         32        394      0.779      0.941       0.81      0.511
             inclusion         38        106      0.643      0.578      0.626      0.277
               patches         30         69      0.751      0.826      0.859      0.494
        pitted_surface         31         43      0.723      0.744      0.782      0.432
       rolled-in_scale         26         57      0.799      0.279      0.523      0.217
             scratches         35         55      0.677      0.873      0.851      0.436
Speed: 0.2ms preprocess, 10.9ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to /root/runs/detect/val
mAP50: 0.742
mAP50-95: 0.395

In [5]:
model.benchmark(source="NEU-DET/images/test/crazing_4.jpg")

Setup complete ✅ (224 CPUs, 754.5 GB RAM, 10.7/30.0 GB disk)

Benchmarks complete for runs/detect/baseline+M1+M2(16)/weights/best.pt on coco8.yaml at imgsz=224 (160.36s)
Benchmarks legend:  - ✅ Success  - ❎ Export passed but validation failed  - ❌️ Export failed
+-----------------------------------------------------------------------------------------------------------+
|      Format                  Status❔   Size (MB)   metrics/mAP50-95(B)   Inference time (ms/im)   FPS    |
+===========================================================================================================+
| 1    PyTorch                 ✅         6.0         0.0                   36.09                    27.71  |
| 2    TorchScript             ✅         11.9        0.0                   3.31                     302.01 |
| 3    ONNX                    ✅         10.1        0.0                   2.6                      384.06 |
| 4    OpenVINO                ❌         0.0         -                     -                        -      |
| 5    TensorRT                ✅         13.2        0.0                   1.0                      996.35 |
| 6    CoreML                  ❌         0.0         -                     -                        -      |
| 7    TensorFlow SavedModel   ✅         25.5        0.0                   84.79                    11.79  |
| 8    TensorFlow GraphDef     ✅         10.1        0.0                   91.63                    10.91  |
| 9    TensorFlow Lite         ❌         0.0         -                     -                        -      |
| 10   TensorFlow Edge TPU     ❌         0.0         -                     -                        -      |
| 11   TensorFlow.js           ❌         0.0         -                     -                        -      |
| 12   PaddlePaddle            ❌         0.0         -                     -                        -      |
| 13   MNN                     ✅         10.1        0.0                   15.08                    66.32  |
| 14   NCNN                    ✅         10.1        0.0                   1027.42                  0.97   |
| 15   IMX                     ❌         0.0         -                     -                        -      |
| 16   RKNN                    ❌         0.0         -                     -                        -      |
| 17   ExecuTorch              ❌         0.0         -                     -                        -      |
| 18   Axelera AI              ❌         0.0         -                     -                        -      |
+-----------------------------------------------------------------------------------------------------------+

+-----------------------------------------------------------------------------------------------------------+
|      Format                  Status❔   Size (MB)   metrics/mAP50-95(B)   Inference time (ms/im)   FPS    |
+===========================================================================================================+
| 1    PyTorch                 ✅         6.0         0.0                   36.09                    27.71  |
| 2    TorchScript             ✅         11.9        0.0                   3.31                     302.01 |
| 3    ONNX                    ✅         10.1        0.0                   2.6                      384.06 |
| 4    OpenVINO                ❌         0.0         -                     -                        -      |
| 5    TensorRT                ✅         13.2        0.0                   1.0                      996.35 |
| 6    CoreML                  ❌         0.0         -                     -                        -      |
| 7    TensorFlow SavedModel   ✅         25.5        0.0                   84.79                    11.79  |
| 8    TensorFlow GraphDef     ✅         10.1        0.0                   91.63                    10.91  |
| 9    TensorFlow Lite         ❌         0.0         -                     -                        -      |
| 10   TensorFlow Edge TPU     ❌         0.0         -                     -                        -      |
| 11   TensorFlow.js           ❌         0.0         -                     -                        -      |
| 12   PaddlePaddle            ❌         0.0         -                     -                        -      |
| 13   MNN                     ✅         10.1        0.0                   15.08                    66.32  |
| 14   NCNN                    ✅         10.1        0.0                   1027.42                  0.97   |
| 15   IMX                     ❌         0.0         -                     -                        -      |
| 16   RKNN                    ❌         0.0         -                     -                        -      |
| 17   ExecuTorch              ❌         0.0         -                     -                        -      |
| 18   Axelera AI              ❌         0.0         -                     -                        -      |
+-----------------------------------------------------------------------------------------------------------+

#### baseline+M1+M2 6*6

In [7]:
from ultralytics import YOLO

# 加载模型
model = YOLO("yaml/baseline+M1+M2.yaml")

# 训练
results = model.train(
    data='neu-det.yaml',
    epochs=200,                # 训练200轮
    imgsz=200,                 # 图片大小200×200
    batch=16,                  # batch size 16
    name='baseline+M1+M2(36)',
    device=0,                 
    
    # 优化器设置
    optimizer='SGD',
    lr0=0.01,                  # 初始学习率0.01
    momentum=0.937,            # SGD动量
    weight_decay=0.0005,       # 权重衰减
    warmup_epochs=3,           # 3轮预热
    warmup_momentum=0.8,       # 预热阶段动量
    
    # 数据增强
    mosaic=1.0,                # Mosaic概率1.0
    copy_paste=0.0,
    mixup=0.0,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,
    degrees=0.0,
    translate=0.1,             # 平移比例0.1
    scale=0.5,                 # 缩放范围0.5
    shear=0.0,
    perspective=0.0,
    flipud=0.0,
    fliplr=0.5,                # 水平翻转概率0.5
    erasing=0.4,               # RandomErasing概率0.4
    augment=True,              # 开启RandAugment
    
    # 训练稳定性配置
    amp=True,
    cache=True,                # 开启缓存加速
    workers=8,                 # 数据加载线程数
    patience=50,               # 早停
    save=True,
    plots=True
)
# 1. 输出参数量 & GFLOPs
model_info = model.info()  # 会自动打印 params, GFLOPs

WARNING ⚠️ no model scale passed. Assuming scale='n'.
New https://pypi.org/project/ultralytics/8.4.46 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.4.43 🚀 Python-3.12.3 torch-2.7.0+cu128 CUDA:0 (NVIDIA GeForce RTX 4090, 48508MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=True, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=True, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=neu-det.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=200, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=200, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yaml/baseline+M1+M2.yaml, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=baseline+M1+M2(36), nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=50, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/root/runs/detect/baseline+M1+M2(36), save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
WARNING ⚠️ no model scale passed. Assuming scale='n'.

                   from  n    params  module                                       arguments
  0                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  1                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  2                  -1  1      5712  ultralytics.nn.modules.block.C3k2            [3, 64, 1, False, 0.25]
  3                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  8                  -1  1    313344  ultralytics.nn.modules.block.C3k2            [128, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1    262144  ultralytics.nn.modules.block.MDLA            [256, 256, 1]
 12                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 13             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 14                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 15                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 16             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 17                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 18                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
 19            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 20                  -1  1    119488  ultralytics.nn.modules.block.C3k2            [448, 128, 1, False]
 21                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
 22            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 23                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 24        [16, 19, 22]  1   1253794  ultralytics.nn.modules.head.Detect           [6, 16, None, [256, 448, 384]]
baseline+M1+M2 summary: 177 layers, 3,004,210 parameters, 3,004,194 gradients, 9.3 GFLOPs

Freezing layer 'model.24.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
WARNING ⚠️ imgsz=[200] must be multiple of max stride 32, updating to [224]
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 632.2±188.7 MB/s, size: 19.0 KB)
train: Scanning /root/NEU-DET/labels/train... 1440 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1440/1440 1.6Kit/s 0.9s0.0s
train: /root/NEU-DET/images/train/inclusion_62.jpg: 1 duplicate labels removed
train: /root/NEU-DET/images/train/patches_198.jpg: 1 duplicate labels removed
train: New cache created: /root/NEU-DET/labels/train.cache
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
train: Caching images (0.2GB RAM): 100% ━━━━━━━━━━━━ 1440/1440 5.5Kit/s 0.3s0.1s
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 218.2±87.2 MB/s, size: 14.4 KB)
val: Scanning /root/NEU-DET/labels/val... 180 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 180/180 1.4Kit/s 0.1s<0.1s
val: New cache created: /root/NEU-DET/labels/val.cache
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
val: Caching images (0.0GB RAM): 100% ━━━━━━━━━━━━ 180/180 4.1Kit/s 0.0s
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 74 weight(decay=0.0), 83 weight(decay=0.0005), 80 bias(decay=0.0)
Plotting labels to /root/runs/detect/baseline+M1+M2(36)/labels.jpg...
Image sizes 224 train, 224 val
Using 8 dataloader workers
Logging results to /root/runs/detect/baseline+M1+M2(36)
Starting training for 200 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/200     0.479G       4.81      4.005      3.798        167        224: 100% ━━━━━━━━━━━━ 90/90 9.8it/s 9.2s<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 13.2it/s 0.5s.1s
                   all        180       1121          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/200     0.533G      4.227      3.072      2.958        168        224: 100% ━━━━━━━━━━━━ 90/90 10.5it/s 8.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.3it/s 0.5s.1s
                   all        180       1121    0.00848      0.069    0.00336    0.00112

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/200     0.543G      3.916      2.995      2.745        202        224: 100% ━━━━━━━━━━━━ 90/90 10.9it/s 8.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.2it/s 0.5s.1s
                   all        180       1121      0.678     0.0217    0.00781    0.00212

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/200     0.545G      3.656      2.858      2.582        133        224: 100% ━━━━━━━━━━━━ 90/90 11.0it/s 8.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.3it/s 0.5s.1s
                   all        180       1121      0.227       0.12     0.0488     0.0125

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/200     0.545G       3.45      2.731      2.493         98        224: 100% ━━━━━━━━━━━━ 90/90 10.9it/s 8.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.8it/s 0.5s.1s
                   all        180       1121      0.573     0.0767     0.0579     0.0158

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/200      0.57G      3.212      2.501      2.307        206        224: 100% ━━━━━━━━━━━━ 90/90 10.9it/s 8.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.9it/s 0.6s.1s
                   all        180       1121      0.263      0.239      0.115     0.0333

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/200      0.58G      3.017      2.346      2.189        177        224: 100% ━━━━━━━━━━━━ 90/90 10.8it/s 8.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.8it/s 0.5s.1s
                   all        180       1121      0.354      0.221      0.165     0.0496

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/200      0.58G      2.874      2.271      2.144        157        224: 100% ━━━━━━━━━━━━ 90/90 10.9it/s 8.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.7it/s 0.5s.1s
                   all        180       1121      0.345      0.257      0.191     0.0577

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/200      0.58G      2.735      2.194      2.086        215        224: 100% ━━━━━━━━━━━━ 90/90 11.0it/s 8.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.6it/s 0.5s.1s
                   all        180       1121      0.221      0.278      0.206     0.0647

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/200      0.58G      2.657       2.15      2.031        205        224: 100% ━━━━━━━━━━━━ 90/90 11.1it/s 8.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.8it/s 0.5s.1s
                   all        180       1121      0.415       0.34      0.265     0.0811

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/200      0.58G      2.569      2.088      1.998        131        224: 100% ━━━━━━━━━━━━ 90/90 10.9it/s 8.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.8it/s 0.5s.1s
                   all        180       1121      0.469      0.235      0.216     0.0749

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/200      0.58G      2.525      2.042       1.94        177        224: 100% ━━━━━━━━━━━━ 90/90 11.2it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.8it/s 0.5s.1s
                   all        180       1121      0.517      0.342       0.35      0.122

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/200      0.58G      2.451      1.996      1.894         87        224: 100% ━━━━━━━━━━━━ 90/90 11.2it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.4it/s 0.5s.1s
                   all        180       1121      0.532      0.316      0.303      0.106

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/200     0.586G      2.393      1.972      1.882        152        224: 100% ━━━━━━━━━━━━ 90/90 11.1it/s 8.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.1it/s 0.5s.1s
                   all        180       1121      0.523      0.363      0.348       0.13

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/200     0.586G      2.371      1.935      1.844        212        224: 100% ━━━━━━━━━━━━ 90/90 11.3it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.2it/s 0.5s.1s
                   all        180       1121      0.489      0.385      0.349      0.133

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/200      0.59G      2.309      1.899      1.831        118        224: 100% ━━━━━━━━━━━━ 90/90 12.2it/s 7.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.1it/s 0.5s.1s
                   all        180       1121      0.523      0.394      0.393      0.165

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/200       0.6G      2.289      1.872      1.802        159        224: 100% ━━━━━━━━━━━━ 90/90 11.8it/s 7.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.1it/s 0.5s.1s
                   all        180       1121      0.516       0.42       0.38      0.144

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/200     0.607G      2.271      1.855      1.784        122        224: 100% ━━━━━━━━━━━━ 90/90 13.5it/s 6.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.4it/s 0.5s.1s
                   all        180       1121      0.498      0.398      0.349      0.148

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/200     0.607G      2.243      1.834      1.781        107        224: 100% ━━━━━━━━━━━━ 90/90 13.8it/s 6.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.6it/s 0.5s.1s
                   all        180       1121      0.609      0.287      0.384      0.157

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/200     0.611G      2.245       1.84       1.79        122        224: 100% ━━━━━━━━━━━━ 90/90 14.0it/s 6.4s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.7it/s 0.5s.1s
                   all        180       1121      0.375      0.496      0.418      0.172

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/200     0.619G      2.212        1.8      1.738        231        224: 100% ━━━━━━━━━━━━ 90/90 13.2it/s 6.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 13.1it/s 0.5s.3s
                   all        180       1121      0.394      0.437      0.393      0.157

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/200     0.619G      2.172      1.784      1.735        146        224: 100% ━━━━━━━━━━━━ 90/90 11.4it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.9it/s 0.5s.1s
                   all        180       1121      0.532      0.474       0.41      0.184

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/200     0.619G      2.158      1.772       1.72        188        224: 100% ━━━━━━━━━━━━ 90/90 10.9it/s 8.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.6it/s 0.5s.1s
                   all        180       1121       0.63      0.447      0.465      0.202

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/200     0.619G      2.169      1.773      1.716        220        224: 100% ━━━━━━━━━━━━ 90/90 12.6it/s 7.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.1it/s 0.5s.1s
                   all        180       1121      0.669      0.403      0.445      0.196

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/200     0.619G      2.145      1.756      1.718        151        224: 100% ━━━━━━━━━━━━ 90/90 12.8it/s 7.1s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.6it/s 0.5s.1s
                   all        180       1121      0.357      0.534      0.454      0.196

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/200     0.619G      2.139      1.759      1.703        210        224: 100% ━━━━━━━━━━━━ 90/90 12.1it/s 7.4s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.4it/s 0.5s.1s
                   all        180       1121      0.589      0.424      0.472      0.209

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/200     0.619G        2.1      1.726      1.683        127        224: 100% ━━━━━━━━━━━━ 90/90 13.3it/s 6.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.3it/s 0.5s.1s
                   all        180       1121      0.607       0.45      0.459      0.207

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/200     0.619G        2.1      1.707      1.685        245        224: 100% ━━━━━━━━━━━━ 90/90 12.0it/s 7.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.4it/s 0.5s.1s
                   all        180       1121      0.412      0.463       0.45      0.203

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/200     0.619G      2.082      1.726      1.679        205        224: 100% ━━━━━━━━━━━━ 90/90 14.0it/s 6.4s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.5it/s 0.5s.1s
                   all        180       1121      0.409      0.486      0.451      0.209

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/200     0.619G      2.086      1.715      1.676        160        224: 100% ━━━━━━━━━━━━ 90/90 11.0it/s 8.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.5it/s 0.5s.1s
                   all        180       1121      0.398      0.542      0.483      0.226

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/200     0.619G      2.064      1.693      1.656        144        224: 100% ━━━━━━━━━━━━ 90/90 11.6it/s 7.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.5it/s 0.5s.1s
                   all        180       1121      0.473      0.528      0.496      0.217

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/200     0.619G      2.051       1.69      1.663        173        224: 100% ━━━━━━━━━━━━ 90/90 14.2it/s 6.4s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.5it/s 0.5s.1s
                   all        180       1121      0.469      0.474      0.513      0.229

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/200     0.619G      2.059      1.666      1.659        145        224: 100% ━━━━━━━━━━━━ 90/90 14.0it/s 6.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.7it/s 0.5s.1s

In [8]:
model = YOLO('runs/detect/baseline+M1+M2(36)/weights/best.pt')
# 评估模型
metrics = model.val(
    data='neu-det.yaml',
    imgsz=200
)

# 打印评估指标
print(f"mAP50: {metrics.box.map50:.3f}")
print(f"mAP50-95: {metrics.box.map:.3f}")

WARNING ⚠️ imgsz=[200] must be multiple of max stride 32, updating to [224]
Ultralytics 8.4.43 🚀 Python-3.12.3 torch-2.7.0+cu128 CUDA:0 (NVIDIA GeForce RTX 4090, 48508MiB)
baseline+M1+M2 summary (fused): 103 layers, 2,994,842 parameters, 0 gradients, 9.2 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 670.6±286.9 MB/s, size: 19.2 KB)
val: Scanning /root/NEU-DET/labels/val.cache... 180 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 180/180 53.9Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 2.7it/s 4.4s<0.1s
                   all        180       1121      0.713       0.71      0.758      0.393
               crazing         32        791      0.599        0.7      0.668      0.282
             inclusion         38        106      0.605      0.708       0.67      0.338
               patches         30         69      0.727      0.841       0.87      0.536
        pitted_surface         31         43      0.808      0.684      0.829      0.442
       rolled-in_scale         26         57      0.718      0.403      0.607      0.258
             scratches         35         55      0.818      0.927      0.904      0.503
Speed: 0.2ms preprocess, 17.9ms inference, 0.0ms loss, 3.1ms postprocess per image
Results saved to /root/runs/detect/val-10
mAP50: 0.758
mAP50-95: 0.393

In [9]:
model.benchmark(source="NEU-DET/images/test/crazing_4.jpg")

Setup complete ✅ (224 CPUs, 754.5 GB RAM, 10.8/30.0 GB disk)

Benchmarks complete for runs/detect/baseline+M1+M2(36)/weights/best.pt on coco8.yaml at imgsz=224 (124.29s)
Benchmarks legend:  - ✅ Success  - ❎ Export passed but validation failed  - ❌️ Export failed
+-----------------------------------------------------------------------------------------------------------+
|      Format                  Status❔   Size (MB)   metrics/mAP50-95(B)   Inference time (ms/im)   FPS    |
+===========================================================================================================+
| 1    PyTorch                 ✅         6.0         0.0                   8.05                     124.19 |
| 2    TorchScript             ✅         11.9        0.0                   3.63                     275.18 |
| 3    ONNX                    ✅         10.1        0.0                   3.02                     331.07 |
| 4    OpenVINO                ❌         0.0         -                     -                        -      |
| 5    TensorRT                ✅         13.1        0.0                   1.09                     919.83 |
| 6    CoreML                  ❌         0.0         -                     -                        -      |
| 7    TensorFlow SavedModel   ✅         25.4        0.0                   115.8                    8.64   |
| 8    TensorFlow GraphDef     ✅         10.1        0.0                   93.86                    10.65  |
| 9    TensorFlow Lite         ❌         0.0         -                     -                        -      |
| 10   TensorFlow Edge TPU     ❌         0.0         -                     -                        -      |
| 11   TensorFlow.js           ❌         0.0         -                     -                        -      |
| 12   PaddlePaddle            ❌         0.0         -                     -                        -      |
| 13   MNN                     ✅         10.1        0.0                   11.66                    85.78  |
| 14   NCNN                    ✅         10.1        0.0                   601.98                   1.66   |
| 15   IMX                     ❌         0.0         -                     -                        -      |
| 16   RKNN                    ❌         0.0         -                     -                        -      |
| 17   ExecuTorch              ❌         0.0         -                     -                        -      |
| 18   Axelera AI              ❌         0.0         -                     -                        -      |
+-----------------------------------------------------------------------------------------------------------+

+-----------------------------------------------------------------------------------------------------------+
|      Format                  Status❔   Size (MB)   metrics/mAP50-95(B)   Inference time (ms/im)   FPS    |
+===========================================================================================================+
| 1    PyTorch                 ✅         6.0         0.0                   8.05                     124.19 |
| 2    TorchScript             ✅         11.9        0.0                   3.63                     275.18 |
| 3    ONNX                    ✅         10.1        0.0                   3.02                     331.07 |
| 4    OpenVINO                ❌         0.0         -                     -                        -      |
| 5    TensorRT                ✅         13.1        0.0                   1.09                     919.83 |
| 6    CoreML                  ❌         0.0         -                     -                        -      |
| 7    TensorFlow SavedModel   ✅         25.4        0.0                   115.8                    8.64   |
| 8    TensorFlow GraphDef     ✅         10.1        0.0                   93.86                    10.65  |
| 9    TensorFlow Lite         ❌         0.0         -                     -                        -      |
| 10   TensorFlow Edge TPU     ❌         0.0         -                     -                        -      |
| 11   TensorFlow.js           ❌         0.0         -                     -                        -      |
| 12   PaddlePaddle            ❌         0.0         -                     -                        -      |
| 13   MNN                     ✅         10.1        0.0                   11.66                    85.78  |
| 14   NCNN                    ✅         10.1        0.0                   601.98                   1.66   |
| 15   IMX                     ❌         0.0         -                     -                        -      |
| 16   RKNN                    ❌         0.0         -                     -                        -      |
| 17   ExecuTorch              ❌         0.0         -                     -                        -      |
| 18   Axelera AI              ❌         0.0         -                     -                        -      |
+-----------------------------------------------------------------------------------------------------------+

#### baseline+M1+M2 recall<0.7 crazing,rolled-in_scale

In [1]:
import os
import numpy as np

# ===================== 配置 =====================
BOTTLENECK_CLASSES = {0,4}  # 瓶颈类别
GRID_SIZE =  2 # 论文里的2×2网格划分

# 原始标签路径
INPUT_TRAIN = "./NEU-DET/labels/train_original"
INPUT_VAL   = "./NEU-DET/labels/val_original"
INPUT_TEST  = "./NEU-DET/labels/test_original"

# 重构后输出路径
OUTPUT_TRAIN = "./NEU-DET/labels/train"
OUTPUT_VAL   = "./NEU-DET/labels/val"
OUTPUT_TEST  = "./NEU-DET/labels/test"

# 自动创建文件夹
os.makedirs(OUTPUT_TRAIN, exist_ok=True)
os.makedirs(OUTPUT_VAL, exist_ok=True)
os.makedirs(OUTPUT_TEST, exist_ok=True)

# ===================== RGA 整图网格划分重构函数 =====================
def rga_reform_grid(txt_path, save_path):
    with open(txt_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    new_lines = []
    # 1. 先读取所有标签
    bboxes = []
    for line in lines:
        line = line.strip()
        if not line:
            continue
        cls, x, y, w, h = map(float, line.split())
        cls = int(cls)
        bboxes.append((cls, x, y, w, h))

    # 2. 生成2×2网格（按整张图片划分）
    grid_w = 1.0 / GRID_SIZE
    grid_h = 1.0 / GRID_SIZE

    # 遍历所有网格
    for i in range(GRID_SIZE):
        for j in range(GRID_SIZE):
            # 计算网格的坐标和尺寸（YOLO格式：x_center, y_center, w, h）
            gx = grid_w * (j + 0.5)
            gy = grid_h * (i + 0.5)
            gw = grid_w
            gh = grid_h

            # 3. 检查这个网格是否和任何瓶颈类缺陷有交集，并记录重叠的类别ID
            overlap_cls = None
            for (cls, x, y, w, h) in bboxes:
                if cls not in BOTTLENECK_CLASSES:
                    continue

                # 计算网格和缺陷框的IOU（简化版交集判断）
                # 网格坐标
                gx1, gy1 = gx - gw/2, gy - gh/2
                gx2, gy2 = gx + gw/2, gy + gh/2
                # 缺陷框坐标
                bx1, by1 = x - w/2, y - h/2
                bx2, by2 = x + w/2, y + h/2

                # 计算交集
                ix1 = max(gx1, bx1)
                iy1 = max(gy1, by1)
                ix2 = min(gx2, bx2)
                iy2 = min(gy2, by2)

                if ix1 < ix2 and iy1 < iy2:
                    overlap_cls = cls  # 保存实际的类别ID，而不是固定0
                    break

            # 4. 如果有交集，就给这个网格打上【原类别标签】
            if overlap_cls is not None:
                new_lines.append(f"{overlap_cls} {gx:.6f} {gy:.6f} {gw:.6f} {gh:.6f}")

    # 5. 保留非瓶颈类的原始标签（完全不变）
    for (cls, x, y, w, h) in bboxes:
        if cls not in BOTTLENECK_CLASSES:
            new_lines.append(f"{cls} {x:.6f} {y:.6f} {w:.6f} {h:.6f}")

    with open(save_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(new_lines))

# ===================== 批量处理三类数据集 =====================
def process_folder(input_dir, output_dir):
    for fname in os.listdir(input_dir):
        if fname.endswith(".txt"):
            rga_reform_grid(
                os.path.join(input_dir, fname),
                os.path.join(output_dir, fname)
            )

process_folder(INPUT_TRAIN, OUTPUT_TRAIN)
process_folder(INPUT_VAL, OUTPUT_VAL)
process_folder(INPUT_TEST, OUTPUT_TEST)

# ===================== 输出信息 =====================
print("RGA标签重构完成！")
print(f"网格划分: {GRID_SIZE}×{GRID_SIZE}")
print(f"瓶颈类别 ID: {sorted(BOTTLENECK_CLASSES)}")

RGA标签重构完成！
网格划分: 2×2
瓶颈类别 ID: [0, 4]

In [2]:
from ultralytics import YOLO

# 加载模型
model = YOLO("yaml/baseline+M1+M2.yaml")

# 训练
results = model.train(
    data='neu-det.yaml',
    epochs=200,                # 训练200轮
    imgsz=200,                 # 图片大小200×200
    batch=16,                  # batch size 16
    name='baseline+M1(0,4)+M2',
    device=0,                 
    
    # 优化器设置
    optimizer='SGD',
    lr0=0.01,                  # 初始学习率0.01
    momentum=0.937,            # SGD动量
    weight_decay=0.0005,       # 权重衰减
    warmup_epochs=3,           # 3轮预热
    warmup_momentum=0.8,       # 预热阶段动量
    
    # 数据增强
    mosaic=1.0,                # Mosaic概率1.0
    copy_paste=0.0,
    mixup=0.0,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,
    degrees=0.0,
    translate=0.1,             # 平移比例0.1
    scale=0.5,                 # 缩放范围0.5
    shear=0.0,
    perspective=0.0,
    flipud=0.0,
    fliplr=0.5,                # 水平翻转概率0.5
    erasing=0.4,               # RandomErasing概率0.4
    augment=True,              # 开启RandAugment
    
    # 训练稳定性配置
    amp=True,
    cache=True,                # 开启缓存加速
    workers=8,                 # 数据加载线程数
    patience=50,               # 早停
    save=True,
    plots=True
)
# 1. 输出参数量 & GFLOPs
model_info = model.info()  # 会自动打印 params, GFLOPs

WARNING ⚠️ no model scale passed. Assuming scale='n'.
New https://pypi.org/project/ultralytics/8.4.46 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.4.43 🚀 Python-3.12.3 torch-2.7.0+cu128 CUDA:0 (NVIDIA GeForce RTX 4090, 48508MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=True, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=True, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=neu-det.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=200, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=200, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yaml/baseline+M1+M2.yaml, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=baseline+M1(0,4)+M2, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=50, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/root/runs/detect/baseline+M1(0,4)+M2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
WARNING ⚠️ no model scale passed. Assuming scale='n'.

                   from  n    params  module                                       arguments
  0                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  1                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  2                  -1  1      5712  ultralytics.nn.modules.block.C3k2            [3, 64, 1, False, 0.25]
  3                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  8                  -1  1    313344  ultralytics.nn.modules.block.C3k2            [128, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1    262144  ultralytics.nn.modules.block.MDLA            [256, 256, 1]
 12                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 13             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 14                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 15                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 16             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 17                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 18                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
 19            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 20                  -1  1    119488  ultralytics.nn.modules.block.C3k2            [448, 128, 1, False]
 21                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
 22            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 23                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 24        [16, 19, 22]  1   1253794  ultralytics.nn.modules.head.Detect           [6, 16, None, [256, 448, 384]]
baseline+M1+M2 summary: 177 layers, 3,004,210 parameters, 3,004,194 gradients, 9.3 GFLOPs

Freezing layer 'model.24.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
WARNING ⚠️ imgsz=[200] must be multiple of max stride 32, updating to [224]
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 748.0±264.6 MB/s, size: 19.0 KB)
train: Scanning /root/NEU-DET/labels/train... 1440 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1440/1440 1.4Kit/s 1.0s0.0s
train: /root/NEU-DET/images/train/inclusion_62.jpg: 1 duplicate labels removed
train: /root/NEU-DET/images/train/patches_198.jpg: 1 duplicate labels removed
train: New cache created: /root/NEU-DET/labels/train.cache
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
train: Caching images (0.2GB RAM): 100% ━━━━━━━━━━━━ 1440/1440 5.9Kit/s 0.2s0.1s
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 741.3±417.0 MB/s, size: 17.3 KB)
val: Scanning /root/NEU-DET/labels/val... 180 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 180/180 1.7Kit/s 0.1s<0.0s
val: New cache created: /root/NEU-DET/labels/val.cache
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
val: Caching images (0.0GB RAM): 100% ━━━━━━━━━━━━ 180/180 3.3Kit/s 0.1s
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 74 weight(decay=0.0), 83 weight(decay=0.0005), 80 bias(decay=0.0)
Plotting labels to /root/runs/detect/baseline+M1(0,4)+M2/labels.jpg...
Image sizes 224 train, 224 val
Using 8 dataloader workers
Logging results to /root/runs/detect/baseline+M1(0,4)+M2
Starting training for 200 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/200     0.445G      3.872      3.926      3.896         79        224: 100% ━━━━━━━━━━━━ 90/90 9.7it/s 9.2s<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.1it/s 0.7s0.1s
                   all        180        480   0.000281      0.167    0.00063   0.000121

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/200     0.471G      3.645      3.158      3.471         75        224: 100% ━━━━━━━━━━━━ 90/90 12.2it/s 7.4s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.1it/s 0.5s.1s
                   all        180        480     0.0079      0.432      0.012    0.00274

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/200      0.48G       3.14      3.019      3.118        102        224: 100% ━━━━━━━━━━━━ 90/90 12.4it/s 7.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.7it/s 0.5s.3s
                   all        180        480      0.364       0.06     0.0328    0.00827

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/200      0.48G      2.684      2.835      2.778         79        224: 100% ━━━━━━━━━━━━ 90/90 12.1it/s 7.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.9it/s 0.5s.1s
                   all        180        480      0.444     0.0895     0.0628     0.0165

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/200      0.48G      2.369      2.615      2.523         83        224: 100% ━━━━━━━━━━━━ 90/90 12.1it/s 7.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.2it/s 0.5s.1s
                   all        180        480      0.188      0.322      0.193     0.0642

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/200      0.48G      2.146      2.376      2.312        101        224: 100% ━━━━━━━━━━━━ 90/90 11.2it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.2it/s 0.5s.1s
                   all        180        480      0.222       0.44      0.263      0.107

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/200      0.49G      1.967      2.197      2.153         83        224: 100% ━━━━━━━━━━━━ 90/90 11.5it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.4it/s 0.5s.1s
                   all        180        480      0.363      0.439       0.36      0.174

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/200     0.492G      1.873      2.064      2.078         91        224: 100% ━━━━━━━━━━━━ 90/90 11.4it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.5it/s 0.5s.1s
                   all        180        480      0.375      0.505      0.405      0.194

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/200     0.492G      1.784      1.983      2.021        113        224: 100% ━━━━━━━━━━━━ 90/90 11.4it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.5it/s 0.5s.1s
                   all        180        480      0.398      0.485      0.357      0.174

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/200     0.492G      1.718      1.915      1.958         91        224: 100% ━━━━━━━━━━━━ 90/90 11.3it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.5it/s 0.5s.1s
                   all        180        480      0.471      0.546      0.494      0.234

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/200     0.492G      1.663      1.839       1.91         75        224: 100% ━━━━━━━━━━━━ 90/90 11.6it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.9it/s 0.5s.3s
                   all        180        480      0.463      0.517      0.405      0.182

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/200     0.492G      1.626      1.788      1.868         91        224: 100% ━━━━━━━━━━━━ 90/90 11.2it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.7it/s 0.5s.1s
                   all        180        480      0.526      0.599      0.561      0.309

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/200     0.492G      1.574       1.71      1.824         71        224: 100% ━━━━━━━━━━━━ 90/90 11.4it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 13.0it/s 0.5s.3s
                   all        180        480      0.501      0.602      0.513      0.244

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/200     0.492G      1.569      1.693      1.823         85        224: 100% ━━━━━━━━━━━━ 90/90 11.3it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.6it/s 0.5s.1s
                   all        180        480      0.518      0.656      0.585      0.306

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/200     0.492G      1.523      1.597      1.773         80        224: 100% ━━━━━━━━━━━━ 90/90 11.2it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.4it/s 0.5s.1s
                   all        180        480      0.567      0.675      0.603      0.314

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/200     0.492G      1.492      1.593      1.748         76        224: 100% ━━━━━━━━━━━━ 90/90 11.3it/s 8.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.8it/s 0.5s.1s
                   all        180        480      0.582      0.659      0.634      0.356

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/200     0.502G      1.484      1.554      1.732         95        224: 100% ━━━━━━━━━━━━ 90/90 11.1it/s 8.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.9it/s 0.5s.3s
                   all        180        480      0.543      0.564      0.543      0.265

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/200     0.512G      1.456      1.507      1.711         84        224: 100% ━━━━━━━━━━━━ 90/90 11.1it/s 8.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.4it/s 0.5s.1s
                   all        180        480      0.579       0.73      0.644       0.36

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/200     0.512G       1.47      1.511      1.719         80        224: 100% ━━━━━━━━━━━━ 90/90 11.4it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.8it/s 0.5s.1s
                   all        180        480       0.64      0.661      0.613      0.332

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/200     0.512G      1.436      1.506      1.701         75        224: 100% ━━━━━━━━━━━━ 90/90 11.5it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.3it/s 0.5s.1s
                   all        180        480      0.658      0.647      0.643      0.331

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/200     0.512G      1.425      1.461      1.682         94        224: 100% ━━━━━━━━━━━━ 90/90 12.1it/s 7.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.4it/s 0.5s.1s
                   all        180        480      0.623      0.689      0.668      0.387

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/200     0.512G      1.392      1.439      1.658         78        224: 100% ━━━━━━━━━━━━ 90/90 11.5it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.6it/s 0.5s.1s
                   all        180        480      0.695      0.722      0.714      0.396

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/200     0.512G      1.411      1.426      1.664         97        224: 100% ━━━━━━━━━━━━ 90/90 12.1it/s 7.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.7it/s 0.5s.1s
                   all        180        480      0.574      0.752       0.69      0.393

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/200     0.512G      1.392      1.425      1.655         97        224: 100% ━━━━━━━━━━━━ 90/90 11.8it/s 7.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.8it/s 0.5s.1s
                   all        180        480      0.612      0.715      0.675      0.391

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/200     0.512G      1.386      1.413      1.655         94        224: 100% ━━━━━━━━━━━━ 90/90 11.5it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 13.1it/s 0.5s.3s
                   all        180        480      0.702      0.726      0.708      0.415

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/200     0.512G      1.359      1.408       1.63         82        224: 100% ━━━━━━━━━━━━ 90/90 11.6it/s 7.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.6it/s 0.5s.1s
                   all        180        480      0.679      0.681      0.676      0.393

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/200     0.512G      1.362      1.367      1.629         87        224: 100% ━━━━━━━━━━━━ 90/90 11.4it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 13.3it/s 0.5s.3s
                   all        180        480      0.624      0.674      0.638      0.334

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/200     0.512G      1.345      1.372      1.611        107        224: 100% ━━━━━━━━━━━━ 90/90 11.4it/s 7.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.5it/s 0.5s.1s
                   all        180        480      0.582      0.661      0.576      0.324

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/200     0.512G      1.355       1.39      1.618         84        224: 100% ━━━━━━━━━━━━ 90/90 12.2it/s 7.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 13.1it/s 0.5s.3s
                   all        180        480      0.675      0.689      0.681      0.396

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/200     0.512G       1.35      1.377      1.618         90        224: 100% ━━━━━━━━━━━━ 90/90 12.0it/s 7.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.8it/s 0.5s.3s
                   all        180        480      0.658       0.74      0.716      0.407

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/200     0.512G      1.309      1.327      1.577         84        224: 100% ━━━━━━━━━━━━ 90/90 11.8it/s 7.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 13.1it/s 0.5s.1s
                   all        180        480      0.769       0.76      0.765      0.429

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/200     0.512G      1.336      1.337      1.596        107        224: 100% ━━━━━━━━━━━━ 90/90 12.6it/s 7.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.8it/s 0.5s.1s
                   all        180        480      0.705       0.74      0.731      0.433

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/200     0.512G      1.315      1.333      1.584         92        224: 100% ━━━━━━━━━━━━ 90/90 11.8it/s 7.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.8it/s 0.5s.1s

In [3]:
model = YOLO('runs/detect/baseline+M1(0,4)+M2/weights/best.pt')
# 评估模型
metrics = model.val(
    data='neu-det.yaml',
    imgsz=200
)

# 打印评估指标
print(f"mAP50: {metrics.box.map50:.3f}")
print(f"mAP50-95: {metrics.box.map:.3f}")

WARNING ⚠️ imgsz=[200] must be multiple of max stride 32, updating to [224]
Ultralytics 8.4.43 🚀 Python-3.12.3 torch-2.7.0+cu128 CUDA:0 (NVIDIA GeForce RTX 4090, 48508MiB)
baseline+M1+M2 summary (fused): 103 layers, 2,994,842 parameters, 0 gradients, 9.2 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 826.5±240.3 MB/s, size: 16.2 KB)
val: Scanning /root/NEU-DET/labels/val.cache... 180 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 180/180 62.9Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 7.1it/s 1.7s0.3s
                   all        180        480      0.852      0.843      0.875      0.602
               crazing         32        116      0.895          1      0.928      0.834
             inclusion         38        106      0.779      0.623      0.703      0.347
               patches         30         69      0.869       0.87      0.907      0.544
        pitted_surface         31         43      0.855      0.674      0.824      0.472
       rolled-in_scale         26         91      0.874          1      0.944      0.844
             scratches         35         55      0.839      0.891      0.941      0.569
Speed: 0.3ms preprocess, 5.7ms inference, 0.0ms loss, 0.6ms postprocess per image
Results saved to /root/runs/detect/val
mAP50: 0.875
mAP50-95: 0.602

In [4]:
model.benchmark(source="NEU-DET/images/test/crazing_4.jpg")

Setup complete ✅ (224 CPUs, 754.5 GB RAM, 10.9/30.0 GB disk)

Benchmarks complete for runs/detect/baseline+M1(0,4)+M2/weights/best.pt on coco8.yaml at imgsz=224 (173.10s)
Benchmarks legend:  - ✅ Success  - ❎ Export passed but validation failed  - ❌️ Export failed
+-----------------------------------------------------------------------------------------------------------+
|      Format                  Status❔   Size (MB)   metrics/mAP50-95(B)   Inference time (ms/im)   FPS    |
+===========================================================================================================+
| 1    PyTorch                 ✅         6.0         0.0                   35.13                    28.47  |
| 2    TorchScript             ✅         11.9        0.0                   3.01                     331.98 |
| 3    ONNX                    ✅         10.1        0.0                   2.86                     349.65 |
| 4    OpenVINO                ❌         0.0         -                     -                        -      |
| 5    TensorRT                ✅         13.0        0.0                   1.14                     874.4  |
| 6    CoreML                  ❌         0.0         -                     -                        -      |
| 7    TensorFlow SavedModel   ✅         25.6        0.0                   88.17                    11.34  |
| 8    TensorFlow GraphDef     ✅         10.1        0.0                   96.49                    10.36  |
| 9    TensorFlow Lite         ❌         0.0         -                     -                        -      |
| 10   TensorFlow Edge TPU     ❌         0.0         -                     -                        -      |
| 11   TensorFlow.js           ❌         0.0         -                     -                        -      |
| 12   PaddlePaddle            ❌         0.0         -                     -                        -      |
| 13   MNN                     ✅         10.1        0.0                   11.87                    84.25  |
| 14   NCNN                    ✅         10.1        0.0                   565.42                   1.77   |
| 15   IMX                     ❌         0.0         -                     -                        -      |
| 16   RKNN                    ❌         0.0         -                     -                        -      |
| 17   ExecuTorch              ❌         0.0         -                     -                        -      |
| 18   Axelera AI              ❌         0.0         -                     -                        -      |
+-----------------------------------------------------------------------------------------------------------+

+-----------------------------------------------------------------------------------------------------------+
|      Format                  Status❔   Size (MB)   metrics/mAP50-95(B)   Inference time (ms/im)   FPS    |
+===========================================================================================================+
| 1    PyTorch                 ✅         6.0         0.0                   35.13                    28.47  |
| 2    TorchScript             ✅         11.9        0.0                   3.01                     331.98 |
| 3    ONNX                    ✅         10.1        0.0                   2.86                     349.65 |
| 4    OpenVINO                ❌         0.0         -                     -                        -      |
| 5    TensorRT                ✅         13.0        0.0                   1.14                     874.4  |
| 6    CoreML                  ❌         0.0         -                     -                        -      |
| 7    TensorFlow SavedModel   ✅         25.6        0.0                   88.17                    11.34  |
| 8    TensorFlow GraphDef     ✅         10.1        0.0                   96.49                    10.36  |
| 9    TensorFlow Lite         ❌         0.0         -                     -                        -      |
| 10   TensorFlow Edge TPU     ❌         0.0         -                     -                        -      |
| 11   TensorFlow.js           ❌         0.0         -                     -                        -      |
| 12   PaddlePaddle            ❌         0.0         -                     -                        -      |
| 13   MNN                     ✅         10.1        0.0                   11.87                    84.25  |
| 14   NCNN                    ✅         10.1        0.0                   565.42                   1.77   |
| 15   IMX                     ❌         0.0         -                     -                        -      |
| 16   RKNN                    ❌         0.0         -                     -                        -      |
| 17   ExecuTorch              ❌         0.0         -                     -                        -      |
| 18   Axelera AI              ❌         0.0         -                     -                        -      |
+-----------------------------------------------------------------------------------------------------------+

#### baseline+M1+M2 recall<0.9 crazing,inclusion,patches,pitted_surface,rolled-in_scale

In [5]:
import os
import numpy as np

# ===================== 配置 =====================
BOTTLENECK_CLASSES = {0,1,2,3,4}  # 瓶颈类别
GRID_SIZE =  2 # 2×2网格划分

# 原始标签路径
INPUT_TRAIN = "./NEU-DET/labels/train_original"
INPUT_VAL   = "./NEU-DET/labels/val_original"
INPUT_TEST  = "./NEU-DET/labels/test_original"

# 重构后输出路径
OUTPUT_TRAIN = "./NEU-DET/labels/train"
OUTPUT_VAL   = "./NEU-DET/labels/val"
OUTPUT_TEST  = "./NEU-DET/labels/test"

# 自动创建文件夹
os.makedirs(OUTPUT_TRAIN, exist_ok=True)
os.makedirs(OUTPUT_VAL, exist_ok=True)
os.makedirs(OUTPUT_TEST, exist_ok=True)

# ===================== RGA 整图网格划分重构函数 =====================
def rga_reform_grid(txt_path, save_path):
    with open(txt_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    new_lines = []
    # 1. 先读取所有标签
    bboxes = []
    for line in lines:
        line = line.strip()
        if not line:
            continue
        cls, x, y, w, h = map(float, line.split())
        cls = int(cls)
        bboxes.append((cls, x, y, w, h))

    # 2. 生成2×2网格（按整张图片划分）
    grid_w = 1.0 / GRID_SIZE
    grid_h = 1.0 / GRID_SIZE

    # 遍历所有网格
    for i in range(GRID_SIZE):
        for j in range(GRID_SIZE):
            # 计算网格的坐标和尺寸（YOLO格式：x_center, y_center, w, h）
            gx = grid_w * (j + 0.5)
            gy = grid_h * (i + 0.5)
            gw = grid_w
            gh = grid_h

            # 3. 检查这个网格是否和任何瓶颈类缺陷有交集，并记录重叠的类别ID
            overlap_cls = None
            for (cls, x, y, w, h) in bboxes:
                if cls not in BOTTLENECK_CLASSES:
                    continue

                # 计算网格和缺陷框的IOU（简化版交集判断）
                # 网格坐标
                gx1, gy1 = gx - gw/2, gy - gh/2
                gx2, gy2 = gx + gw/2, gy + gh/2
                # 缺陷框坐标
                bx1, by1 = x - w/2, y - h/2
                bx2, by2 = x + w/2, y + h/2

                # 计算交集
                ix1 = max(gx1, bx1)
                iy1 = max(gy1, by1)
                ix2 = min(gx2, bx2)
                iy2 = min(gy2, by2)

                if ix1 < ix2 and iy1 < iy2:
                    overlap_cls = cls  # 保存实际的类别ID，而不是固定0
                    break

            # 4. 如果有交集，就给这个网格打上【原类别标签】
            if overlap_cls is not None:
                new_lines.append(f"{overlap_cls} {gx:.6f} {gy:.6f} {gw:.6f} {gh:.6f}")

    # 5. 保留非瓶颈类的原始标签（完全不变）
    for (cls, x, y, w, h) in bboxes:
        if cls not in BOTTLENECK_CLASSES:
            new_lines.append(f"{cls} {x:.6f} {y:.6f} {w:.6f} {h:.6f}")

    with open(save_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(new_lines))

# ===================== 批量处理三类数据集 =====================
def process_folder(input_dir, output_dir):
    for fname in os.listdir(input_dir):
        if fname.endswith(".txt"):
            rga_reform_grid(
                os.path.join(input_dir, fname),
                os.path.join(output_dir, fname)
            )

process_folder(INPUT_TRAIN, OUTPUT_TRAIN)
process_folder(INPUT_VAL, OUTPUT_VAL)
process_folder(INPUT_TEST, OUTPUT_TEST)

# ===================== 输出信息 =====================
print("RGA标签重构完成！")
print(f"网格划分: {GRID_SIZE}×{GRID_SIZE}")
print(f"瓶颈类别 ID: {sorted(BOTTLENECK_CLASSES)}")

RGA标签重构完成！
网格划分: 2×2
瓶颈类别 ID: [0, 1, 2, 3, 4]

In [6]:
from ultralytics import YOLO

# 加载模型
model = YOLO("yaml/baseline+M1+M2.yaml")

# 训练
results = model.train(
    data='neu-det.yaml',
    epochs=200,                # 训练200轮
    imgsz=200,                 # 图片大小200×200
    batch=16,                  # batch size 16
    name='baseline+M1(0,1,2,3,4)+M2',
    device=0,                 
    
    # 优化器设置
    optimizer='SGD',
    lr0=0.01,                  # 初始学习率0.01
    momentum=0.937,            # SGD动量
    weight_decay=0.0005,       # 权重衰减
    warmup_epochs=3,           # 3轮预热
    warmup_momentum=0.8,       # 预热阶段动量
    
    # 数据增强
    mosaic=1.0,                # Mosaic概率1.0
    copy_paste=0.0,
    mixup=0.0,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,
    degrees=0.0,
    translate=0.1,             # 平移比例0.1
    scale=0.5,                 # 缩放范围0.5
    shear=0.0,
    perspective=0.0,
    flipud=0.0,
    fliplr=0.5,                # 水平翻转概率0.5
    erasing=0.4,               # RandomErasing概率0.4
    augment=True,              # 开启RandAugment
    
    # 训练稳定性配置
    amp=True,
    cache=True,                # 开启缓存加速
    workers=8,                 # 数据加载线程数
    patience=50,               # 早停
    save=True,
    plots=True
)
# 1. 输出参数量 & GFLOPs
model_info = model.info()  # 会自动打印 params, GFLOPs

WARNING ⚠️ no model scale passed. Assuming scale='n'.
New https://pypi.org/project/ultralytics/8.4.46 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.4.43 🚀 Python-3.12.3 torch-2.7.0+cu128 CUDA:0 (NVIDIA GeForce RTX 4090, 48508MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=True, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=True, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=neu-det.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=200, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=200, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yaml/baseline+M1+M2.yaml, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=baseline+M1(0,1,2,3,4)+M2, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=50, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/root/runs/detect/baseline+M1(0,1,2,3,4)+M2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
WARNING ⚠️ no model scale passed. Assuming scale='n'.

                   from  n    params  module                                       arguments
  0                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  1                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  2                  -1  1      5712  ultralytics.nn.modules.block.C3k2            [3, 64, 1, False, 0.25]
  3                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
  8                  -1  1    313344  ultralytics.nn.modules.block.C3k2            [128, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1    262144  ultralytics.nn.modules.block.MDLA            [256, 256, 1]
 12                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 13             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 14                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 15                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 16             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 17                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 18                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
 19            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 20                  -1  1    119488  ultralytics.nn.modules.block.C3k2            [448, 128, 1, False]
 21                  -1  1         0  torch.nn.modules.pooling.AvgPool2d           [3, 2, 1]
 22            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 23                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 24        [16, 19, 22]  1   1253794  ultralytics.nn.modules.head.Detect           [6, 16, None, [256, 448, 384]]
baseline+M1+M2 summary: 177 layers, 3,004,210 parameters, 3,004,194 gradients, 9.3 GFLOPs

Freezing layer 'model.24.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
WARNING ⚠️ imgsz=[200] must be multiple of max stride 32, updating to [224]
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 884.4±306.1 MB/s, size: 19.0 KB)
train: Scanning /root/NEU-DET/labels/train... 1440 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1440/1440 1.6Kit/s 0.9s0.0s
train: New cache created: /root/NEU-DET/labels/train.cache
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
train: Caching images (0.2GB RAM): 100% ━━━━━━━━━━━━ 1440/1440 5.7Kit/s 0.3s0.1s
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 247.4±93.9 MB/s, size: 14.4 KB)
val: Scanning /root/NEU-DET/labels/val... 180 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 180/180 1.5Kit/s 0.1s<0.1s
val: New cache created: /root/NEU-DET/labels/val.cache
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
val: Caching images (0.0GB RAM): 100% ━━━━━━━━━━━━ 180/180 4.1Kit/s 0.0s
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 74 weight(decay=0.0), 83 weight(decay=0.0005), 80 bias(decay=0.0)
Plotting labels to /root/runs/detect/baseline+M1(0,1,2,3,4)+M2/labels.jpg...
Image sizes 224 train, 224 val
Using 8 dataloader workers
Logging results to /root/runs/detect/baseline+M1(0,1,2,3,4)+M2
Starting training for 200 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/200     0.502G      3.589      3.864      3.814        108        224: 100% ━━━━━━━━━━━━ 90/90 9.8it/s 9.2s<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.5it/s 0.5s.1s
                   all        180        586   0.000371      0.155    0.00246   0.000434

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/200     0.512G      3.294      3.026      3.315         94        224: 100% ━━━━━━━━━━━━ 90/90 10.4it/s 8.6s.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.4it/s 0.5s.1s
                   all        180        586    0.00708      0.609     0.0156    0.00454

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/200     0.514G      2.708      2.914      2.894        113        224: 100% ━━━━━━━━━━━━ 90/90 10.1it/s 8.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.8it/s 0.5s.1s
                   all        180        586      0.206     0.0845      0.022    0.00641

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/200     0.514G      2.251      2.745      2.527        100        224: 100% ━━━━━━━━━━━━ 90/90 11.0it/s 8.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.8it/s 0.5s.1s
                   all        180        586      0.138      0.299      0.114     0.0483

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/200     0.514G       1.95      2.556      2.271         99        224: 100% ━━━━━━━━━━━━ 90/90 10.9it/s 8.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.1it/s 0.5s.1s
                   all        180        586      0.136      0.286      0.131     0.0618

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/200     0.514G      1.726      2.361       2.06        130        224: 100% ━━━━━━━━━━━━ 90/90 10.8it/s 8.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.2it/s 0.5s.1s
                   all        180        586      0.242      0.454      0.236      0.113

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/200     0.514G      1.586      2.158       1.91        103        224: 100% ━━━━━━━━━━━━ 90/90 11.1it/s 8.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.3it/s 0.5s.1s
                   all        180        586      0.399      0.293      0.212      0.115

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/200     0.514G      1.474      2.011      1.842        120        224: 100% ━━━━━━━━━━━━ 90/90 10.7it/s 8.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.3it/s 0.5s.1s
                   all        180        586      0.235      0.432      0.215      0.104

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/200     0.514G      1.417      1.931      1.794        136        224: 100% ━━━━━━━━━━━━ 90/90 10.9it/s 8.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.6it/s 0.5s.1s
                   all        180        586       0.46      0.548      0.502      0.296

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/200     0.514G      1.354      1.834      1.718        115        224: 100% ━━━━━━━━━━━━ 90/90 10.7it/s 8.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.0it/s 0.5s.1s
                   all        180        586      0.303      0.525      0.301      0.164

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/200     0.514G      1.305      1.765      1.689        101        224: 100% ━━━━━━━━━━━━ 90/90 10.5it/s 8.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.6it/s 0.5s.1s
                   all        180        586      0.421      0.542       0.43      0.248

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/200     0.514G      1.263      1.702      1.656        109        224: 100% ━━━━━━━━━━━━ 90/90 10.5it/s 8.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.9it/s 0.5s.1s
                   all        180        586       0.48      0.507      0.458      0.272

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/200     0.514G      1.217      1.662      1.617        100        224: 100% ━━━━━━━━━━━━ 90/90 10.7it/s 8.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 13.2it/s 0.5s.3s
                   all        180        586      0.424      0.632      0.473      0.274

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/200     0.514G        1.2      1.645      1.592        111        224: 100% ━━━━━━━━━━━━ 90/90 10.9it/s 8.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.1it/s 0.5s.1s
                   all        180        586      0.566      0.628      0.592      0.378

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/200     0.514G       1.16      1.567      1.547        118        224: 100% ━━━━━━━━━━━━ 90/90 10.5it/s 8.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.6it/s 0.5s.1s
                   all        180        586      0.518      0.705      0.617      0.371

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/200     0.514G      1.125      1.535       1.53         98        224: 100% ━━━━━━━━━━━━ 90/90 10.7it/s 8.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.5it/s 0.5s.1s
                   all        180        586      0.607      0.721      0.694      0.473

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/200     0.514G      1.099      1.499       1.51        117        224: 100% ━━━━━━━━━━━━ 90/90 10.6it/s 8.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.7it/s 0.5s.1s
                   all        180        586      0.566      0.693      0.642      0.343

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/200     0.514G      1.074      1.472      1.482        100        224: 100% ━━━━━━━━━━━━ 90/90 10.9it/s 8.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.7it/s 0.5s.1s
                   all        180        586      0.499      0.637      0.528      0.353

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/200     0.514G       1.07      1.465      1.488         97        224: 100% ━━━━━━━━━━━━ 90/90 10.8it/s 8.3s.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.7it/s 0.5s.1s
                   all        180        586      0.602       0.71      0.688      0.412

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/200     0.514G      1.041      1.457      1.469         90        224: 100% ━━━━━━━━━━━━ 90/90 11.0it/s 8.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.6it/s 0.5s.1s
                   all        180        586      0.579      0.676      0.668      0.375

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/200     0.514G      1.032      1.432      1.458        129        224: 100% ━━━━━━━━━━━━ 90/90 10.9it/s 8.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.7it/s 0.5s.1s
                   all        180        586      0.553      0.672      0.606      0.329

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/200     0.514G      1.008      1.402      1.438         97        224: 100% ━━━━━━━━━━━━ 90/90 10.9it/s 8.2s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.2it/s 0.5s.1s
                   all        180        586      0.555      0.655      0.608      0.384

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/200     0.514G      1.022      1.406      1.447        116        224: 100% ━━━━━━━━━━━━ 90/90 10.7it/s 8.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.9it/s 0.5s.1s
                   all        180        586      0.536       0.69      0.628      0.386

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/200     0.514G      1.003      1.388      1.443        120        224: 100% ━━━━━━━━━━━━ 90/90 11.1it/s 8.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.4it/s 0.5s.1s
                   all        180        586       0.64      0.695      0.696      0.433

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/200     0.514G     0.9948      1.403      1.424        111        224: 100% ━━━━━━━━━━━━ 90/90 11.0it/s 8.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.8it/s 0.5s.1s
                   all        180        586       0.62      0.743      0.653      0.448

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/200     0.514G     0.9787      1.358       1.42        102        224: 100% ━━━━━━━━━━━━ 90/90 10.8it/s 8.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.3it/s 0.5s.1s
                   all        180        586      0.607      0.687      0.653      0.443

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/200     0.514G     0.9557      1.335      1.397        101        224: 100% ━━━━━━━━━━━━ 90/90 10.9it/s 8.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.7it/s 0.5s.1s
                   all        180        586      0.722      0.731      0.742      0.524

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/200     0.514G     0.9645      1.327      1.403        134        224: 100% ━━━━━━━━━━━━ 90/90 11.0it/s 8.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.5it/s 0.5s.1s
                   all        180        586       0.71      0.738      0.749      0.531

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/200     0.514G     0.9567      1.326      1.392        111        224: 100% ━━━━━━━━━━━━ 90/90 10.7it/s 8.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.8it/s 0.5s.1s
                   all        180        586      0.599      0.782      0.639      0.437

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/200     0.514G     0.9504      1.315      1.402        109        224: 100% ━━━━━━━━━━━━ 90/90 10.6it/s 8.5s.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.3it/s 0.5s.1s
                   all        180        586      0.689       0.74      0.734      0.503

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/200     0.514G     0.9162      1.298      1.362        108        224: 100% ━━━━━━━━━━━━ 90/90 10.9it/s 8.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 13.3it/s 0.5s.3s
                   all        180        586      0.692      0.738      0.754      0.498

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/200     0.514G     0.9375      1.314      1.382        134        224: 100% ━━━━━━━━━━━━ 90/90 10.7it/s 8.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 12.8it/s 0.5s.1s
                   all        180        586      0.702       0.79      0.765      0.533

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/200     0.514G     0.9265      1.277      1.369        119        224: 100% ━━━━━━━━━━━━ 90/90 10.7it/s 8.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 13.6it/s 0.4s.3s
                   all        180        586      0.708        0.8      0.801      0.612

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

In [7]:
model = YOLO('runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.pt')
# 评估模型
metrics = model.val(
    data='neu-det.yaml',
    imgsz=200
)

# 打印评估指标
print(f"mAP50: {metrics.box.map50:.3f}")
print(f"mAP50-95: {metrics.box.map:.3f}")

WARNING ⚠️ imgsz=[200] must be multiple of max stride 32, updating to [224]
Ultralytics 8.4.43 🚀 Python-3.12.3 torch-2.7.0+cu128 CUDA:0 (NVIDIA GeForce RTX 4090, 48508MiB)
baseline+M1+M2 summary (fused): 103 layers, 2,994,842 parameters, 0 gradients, 9.2 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 934.3±180.6 MB/s, size: 19.2 KB)
val: Scanning /root/NEU-DET/labels/val.cache... 180 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 180/180 58.1Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 7.7it/s 1.6s0.3s
                   all        180        586      0.834      0.923      0.921      0.804
               crazing         32        116      0.775          1      0.923      0.862
             inclusion         35        110      0.791      0.909      0.916      0.831
               patches         25         90      0.916      0.967      0.979        0.9
        pitted_surface         31        124      0.814      0.952      0.973       0.89
       rolled-in_scale         26         91      0.838          1      0.925      0.859
             scratches         35         55      0.867       0.71      0.811      0.481
Speed: 0.3ms preprocess, 4.9ms inference, 0.0ms loss, 0.6ms postprocess per image
Results saved to /root/runs/detect/val-10
mAP50: 0.921
mAP50-95: 0.804

In [ ]:
model.benchmark(source="NEU-DET/images/test/crazing_4.jpg")

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 757.3±156.4 MB/s, size: 54.0 KB)
val: Scanning /root/datasets/coco8/labels/val.cache... 4 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 4/4 883.0Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 72.3it/s 0.1s
                   all          4         17          0          0          0          0
Speed: 0.3ms preprocess, 9.1ms inference, 0.0ms loss, 0.9ms postprocess per image

PyTorch: starting from 'runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.pt' with input shape (1, 3, 224, 224) BCHW and output shape(s) (1, 10, 1029) (6.0 MB)

TorchScript: starting export with torch 2.7.0+cu128...
TorchScript: export success ✅ 1.6s, saved as 'runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.torchscript' (11.9 MB)

Export complete (1.6s)
Results saved to /root/runs/detect/baseline+M1(0,1,2,3,4)+M2/weights
Predict:         yolo predict task=detect model=runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.torchscript imgsz=224
Validate:        yolo val task=detect model=runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.torchscript imgsz=224 data=neu-det.yaml
Visualize:       https://netron.app
Loading runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.torchscript for TorchScript inference...
Loading runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.torchscript for TorchScript inference...
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1835.9±684.1 MB/s, size: 54.0 KB)
val: Scanning /root/datasets/coco8/labels/val.cache... 4 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 4/4 1.4Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 104.0it/s 0.0s
                   all          4         17          0          0          0          0
Speed: 0.3ms preprocess, 3.5ms inference, 0.0ms loss, 0.9ms postprocess per image

PyTorch: starting from 'runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.pt' with input shape (1, 3, 224, 224) BCHW and output shape(s) (1, 10, 1029) (6.0 MB)

ONNX: starting export with onnx 1.21.0 opset 17...
ONNX: slimming with onnxslim 0.1.92...
ONNX: export success ✅ 1.3s, saved as 'runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.onnx' (10.1 MB)

Export complete (1.3s)
Results saved to /root/runs/detect/baseline+M1(0,1,2,3,4)+M2/weights
Predict:         yolo predict task=detect model=runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.onnx imgsz=224
Validate:        yolo val task=detect model=runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.onnx imgsz=224 data=neu-det.yaml
Visualize:       https://netron.app
Loading runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.onnx for ONNX Runtime inference...
Using ONNX Runtime 1.25.1 with CUDAExecutionProvider
Loading runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.onnx for ONNX Runtime inference...
Using ONNX Runtime 1.25.1 with CUDAExecutionProvider
Setting batch=1 input of shape (1, 3, 224, 224)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1034.6±401.3 MB/s, size: 54.0 KB)
val: Scanning /root/datasets/coco8/labels/val.cache... 4 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 4/4 762.6Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 107.7it/s 0.0s
                   all          4         17          0          0          0          0
Speed: 0.3ms preprocess, 2.8ms inference, 0.0ms loss, 1.1ms postprocess per image
ERROR ❌ Benchmark failure for OpenVINO: inference not supported on GPU

PyTorch: starting from 'runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.pt' with input shape (1, 3, 224, 224) BCHW and output shape(s) (1, 10, 1029) (6.0 MB)

ONNX: starting export with onnx 1.21.0 opset 17...
ONNX: slimming with onnxslim 0.1.92...
ONNX: export success ✅ 2.2s, saved as 'runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.onnx' (10.1 MB)

TensorRT: starting export with TensorRT 10.16.1.11...
MNN use low precision
MNN use low precision
[05/06/2026-11:50:05] [TRT] [I] ----------------------------------------------------------------
[05/06/2026-11:50:05] [TRT] [I] Input filename:   runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.onnx
[05/06/2026-11:50:05] [TRT] [I] ONNX IR version:  0.0.8
[05/06/2026-11:50:05] [TRT] [I] Opset version:    17
[05/06/2026-11:50:05] [TRT] [I] Producer name:    pytorch
[05/06/2026-11:50:05] [TRT] [I] Producer version: 2.7.0
[05/06/2026-11:50:05] [TRT] [I] Domain:
[05/06/2026-11:50:05] [TRT] [I] Model version:    0
[05/06/2026-11:50:05] [TRT] [I] Doc string:
[05/06/2026-11:50:05] [TRT] [I] ----------------------------------------------------------------
TensorRT: input "images" with shape(1, 3, 224, 224) DataType.FLOAT
TensorRT: output "output0" with shape(1, 10, 1029) DataType.FLOAT
TensorRT: building FP32 engine as runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.engine
[05/06/2026-11:50:06] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU -269, GPU +0, now: CPU 8740, GPU 47072 (MiB)
[05/06/2026-11:50:06] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[05/06/2026-11:50:27] [TRT] [I] Compiler backend is used during engine build.
[05/06/2026-11:51:03] [TRT] [I] Detected 1 inputs and 3 output network tensors.
[05/06/2026-11:51:03] [TRT] [I] Total Host Persistent Memory: 446496 bytes
[05/06/2026-11:51:03] [TRT] [I] Total Device Persistent Memory: 0 bytes
[05/06/2026-11:51:03] [TRT] [I] Max Scratch Memory: 281600 bytes
[05/06/2026-11:51:03] [TRT] [I] [BlockAssignment] Started assigning block shifts. This will take 203 steps to complete.
[05/06/2026-11:51:03] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 13.0612ms to assign 10 blocks to 203 nodes requiring 3336704 bytes.
[05/06/2026-11:51:03] [TRT] [I] Total Activation Memory: 3336704 bytes
[05/06/2026-11:51:03] [TRT] [I] Total Weights Memory: 12457368 bytes
[05/06/2026-11:51:03] [TRT] [I] Compiler backend is used during engine execution.
[05/06/2026-11:51:03] [TRT] [I] Engine generation completed in 57.4726 seconds.
[05/06/2026-11:51:03] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 1 MiB, GPU 29 MiB
TensorRT: export success ✅ 60.8s, saved as 'runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.engine' (13.2 MB)

Export complete (60.9s)
Results saved to /root/runs/detect/baseline+M1(0,1,2,3,4)+M2/weights
Predict:         yolo predict task=detect model=runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.engine imgsz=224
Validate:        yolo val task=detect model=runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.engine imgsz=224 data=neu-det.yaml
Visualize:       https://netron.app
Loading runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.engine for TensorRT inference...
[05/06/2026-11:51:04] [TRT] [I] Loaded engine size: 13 MiB
[05/06/2026-11:51:04] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +4, now: CPU 0, GPU 15 (MiB)
Loading runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.engine for TensorRT inference...
[05/06/2026-11:51:04] [TRT] [W] WARNING The logger passed into createInferRuntime differs from one already registered for an existing builder, runtime, or refitter. So the current new logger is ignored, and TensorRT will use the existing one which is returned by nvinfer1::getLogger() instead.
[05/06/2026-11:51:04] [TRT] [I] Loaded engine size: 13 MiB
[05/06/2026-11:51:04] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +1, GPU +4, now: CPU 1, GPU 30 (MiB)
Setting batch=1 input of shape (1, 3, 224, 224)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1813.5±808.0 MB/s, size: 54.0 KB)
val: Scanning /root/datasets/coco8/labels/val.cache... 4 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 4/4 699.1Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 113.9it/s 0.0s
                   all          4         17          0          0          0          0
Speed: 0.2ms preprocess, 0.9ms inference, 0.0ms loss, 0.8ms postprocess per image
ERROR ❌ Benchmark failure for CoreML: inference not supported on GPU

PyTorch: starting from 'runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.pt' with input shape (1, 3, 224, 224) BCHW and output shape(s) (1, 10, 1029) (6.0 MB)

ONNX: starting export with onnx 1.21.0 opset 17...
ONNX: slimming with onnxslim 0.1.92...
ONNX: export success ✅ 1.0s, saved as 'runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.onnx' (10.1 MB)

TensorFlow SavedModel: starting export with tensorflow 2.19.0...
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.28.8...
Saved artifact at 'runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best_saved_model'. The following endpoints are available:

* Endpoint 'serving_default'
  inputs_0 (POSITIONAL_ONLY): TensorSpec(shape=(1, 224, 224, 3), dtype=tf.float32, name='images')
Output Type:
  TensorSpec(shape=(1, 10, 1029), dtype=tf.float32, name=None)
Captures:
  139670425431184: TensorSpec(shape=(1, 1, 3, 32), dtype=tf.float32, name=None)
  139670425434640: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  139670425426384: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670425427728: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670425427344: TensorSpec(shape=(3, 3, 16, 8), dtype=tf.float32, name=None)
  139670425420816: TensorSpec(shape=(8,), dtype=tf.float32, name=None)
  139670425435984: TensorSpec(shape=(3, 3, 8, 16), dtype=tf.float32, name=None)
  139670425433488: TensorSpec(shape=(16,), dtype=tf.float32, name=None)
  139670425428112: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670425430416: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670425430032: TensorSpec(shape=(1, 1, 48, 64), dtype=tf.float32, name=None)
  139670425419856: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670425422352: TensorSpec(shape=(1, 1, 64, 64), dtype=tf.float32, name=None)
  139670425421392: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670425420624: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670425428304: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670425422544: TensorSpec(shape=(3, 3, 32, 16), dtype=tf.float32, name=None)
  139670425429456: TensorSpec(shape=(16,), dtype=tf.float32, name=None)
  139670425431568: TensorSpec(shape=(3, 3, 16, 32), dtype=tf.float32, name=None)
  139670425427152: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  139670425425424: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670425433872: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670425420048: TensorSpec(shape=(1, 1, 96, 128), dtype=tf.float32, name=None)
  139670425425616: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  139670425435216: TensorSpec(shape=(1, 1, 128, 128), dtype=tf.float32, name=None)
  139670425425040: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  139670425423312: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670425422928: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670425420432: TensorSpec(shape=(1, 1, 64, 32), dtype=tf.float32, name=None)
  139670425435600: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  139670425431760: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  139670425428880: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  139670425426192: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  139670425434064: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  139670425426960: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  139670425424656: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  139670425429072: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  139670425423120: TensorSpec(shape=(1, 1, 64, 32), dtype=tf.float32, name=None)
  139669590538000: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  139670425420240: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  139669590539920: TensorSpec(shape=(1, 1, 64, 64), dtype=tf.float32, name=None)
  139669590531280: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670425421008: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670425421968: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139669590528016: TensorSpec(shape=(1, 1, 192, 128), dtype=tf.float32, name=None)
  139670347339280: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  139670347337936: TensorSpec(shape=(1, 1, 128, 256), dtype=tf.float32, name=None)
  139670347338704: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  139670347340432: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670347337552: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670347338128: TensorSpec(shape=(1, 1, 128, 64), dtype=tf.float32, name=None)
  139670347342160: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670347341008: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  139670347341776: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670347339088: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  139670347341584: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670347340816: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  139670347342352: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670347339664: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  139670347338896: TensorSpec(shape=(1, 1, 128, 64), dtype=tf.float32, name=None)
  139670347342544: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670347340240: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670347347920: TensorSpec(shape=(1, 1, 128, 128), dtype=tf.float32, name=None)
  139670347343120: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  139670347339472: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670347337360: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670347346576: TensorSpec(shape=(1, 1, 384, 256), dtype=tf.float32, name=None)
  139670347341968: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  139670347346384: TensorSpec(shape=(1, 1, 256, 128), dtype=tf.float32, name=None)
  139670347344272: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  139670347342928: TensorSpec(shape=(1, 1, 512, 256), dtype=tf.float32, name=None)
  139670347343888: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  139670347343312: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  139670347341200: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  139670347345808: TensorSpec(shape=(1, 1, 128, 256), dtype=tf.float32, name=None)
  139670347342736: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  139670347345040: TensorSpec(shape=(), dtype=tf.resource, name=None)
  139670347346192: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  139670347345616: TensorSpec(shape=(1, 1, 128, 128), dtype=tf.float32, name=None)
  139670347343504: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  139670347348112: TensorSpec(shape=(1, 1, 128, 256), dtype=tf.float32, name=None)
  139670347344464: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  139670347344848: TensorSpec(shape=(1, 1, 256, 128), dtype=tf.float32, name=None)
  139670347347728: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  139670347345424: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  139670347341392: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  139670347346768: TensorSpec(shape=(1, 1, 256, 768), dtype=tf.float32, name=None)
  139670347344080: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670347346000: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670347347152: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670347348880: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670347338320: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670347349456: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670347349840: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  139670347333712: TensorSpec(shape=(1, 1, 384, 128), dtype=tf.float32, name=None)
  139670347334480: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  139670347334864: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670347345232: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670347335248: TensorSpec(shape=(3, 3, 64, 32), dtype=tf.float32, name=None)
  139670347335632: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  139670347344656: TensorSpec(shape=(3, 3, 32, 64), dtype=tf.float32, name=None)
  139670347347344: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670347336592: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670347349264: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670347335824: TensorSpec(shape=(1, 1, 192, 128), dtype=tf.float32, name=None)
  139670347336016: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  139670347346960: TensorSpec(shape=(1, 1, 256, 64), dtype=tf.float32, name=None)
  139670347334096: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670381979088: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670381979472: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670381976976: TensorSpec(shape=(3, 3, 32, 16), dtype=tf.float32, name=None)
  139670381969488: TensorSpec(shape=(16,), dtype=tf.float32, name=None)
  139670381976208: TensorSpec(shape=(3, 3, 16, 32), dtype=tf.float32, name=None)
  139670381970832: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  139670381978704: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670381976016: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670381974672: TensorSpec(shape=(1, 1, 96, 64), dtype=tf.float32, name=None)
  139670381971216: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670381972752: TensorSpec(shape=(1, 1, 448, 128), dtype=tf.float32, name=None)
  139670381971984: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  139670381972176: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670381978512: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670381977552: TensorSpec(shape=(3, 3, 64, 32), dtype=tf.float32, name=None)
  139670381981584: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  139670381980432: TensorSpec(shape=(3, 3, 32, 64), dtype=tf.float32, name=None)
  139670381980816: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670381970448: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670381969872: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  139670381981392: TensorSpec(shape=(1, 1, 192, 128), dtype=tf.float32, name=None)
  139670381977360: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  139660320549840: TensorSpec(shape=(3, 3, 384, 64), dtype=tf.float32, name=None)
  139670381975824: TensorSpec(shape=(3, 3, 448, 64), dtype=tf.float32, name=None)
  139670347336400: TensorSpec(shape=(3, 3, 256, 64), dtype=tf.float32, name=None)
  139669590528784: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670381970064: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670347334672: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670425422736: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  139670381971408: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  139670347337168: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  139670425423888: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670381981776: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670381978128: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  139670425433104: TensorSpec(shape=(3, 3, 384, 1), dtype=tf.float32, name=None)
  139670381976784: TensorSpec(shape=(3, 3, 448, 1), dtype=tf.float32, name=None)
  139670347336784: TensorSpec(shape=(3, 3, 256, 1), dtype=tf.float32, name=None)

I0000 00:00:1778039479.210543    1489 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
I0000 00:00:1778039479.210766    1489 single_machine.cc:374] Starting new session
I0000 00:00:1778039479.215575    1489 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 45931 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:16:00.0, compute capability: 8.9
W0000 00:00:1778039479.793742    1489 tf_tfl_flatbuffer_helpers.cc:365] Ignored output_format.
W0000 00:00:1778039479.793770    1489 tf_tfl_flatbuffer_helpers.cc:368] Ignored drop_control_dependency.
I0000 00:00:1778039480.493254    1489 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
I0000 00:00:1778039480.493412    1489 single_machine.cc:374] Starting new session
I0000 00:00:1778039480.498689    1489 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 45931 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:16:00.0, compute capability: 8.9
W0000 00:00:1778039481.149469    1489 tf_tfl_flatbuffer_helpers.cc:365] Ignored output_format.
W0000 00:00:1778039481.149501    1489 tf_tfl_flatbuffer_helpers.cc:368] Ignored drop_control_dependency.

TensorFlow SavedModel: export success ✅ 16.2s, saved as 'runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best_saved_model' (25.4 MB)

Export complete (16.3s)
Results saved to /root/runs/detect/baseline+M1(0,1,2,3,4)+M2/weights
Predict:         yolo predict task=detect model=runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best_saved_model imgsz=224
Validate:        yolo val task=detect model=runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best_saved_model imgsz=224 data=neu-det.yaml
Visualize:       https://netron.app
Loading runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best_saved_model for TensorFlow SavedModel inference...
Loading runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best_saved_model for TensorFlow SavedModel inference...
Setting batch=1 input of shape (1, 3, 224, 224)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1934.8±607.1 MB/s, size: 54.0 KB)
val: Scanning /root/datasets/coco8/labels/val.cache... 4 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 4/4 578.5Kit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 8.6it/s 0.5s4.2s
                   all          4         17          0          0          0          0
Speed: 0.2ms preprocess, 110.6ms inference, 0.0ms loss, 0.7ms postprocess per image

PyTorch: starting from 'runs/detect/baseline+M1(0,1,2,3,4)+M2/weights/best.pt' with input shape (1, 3, 224, 224) BCHW and output shape(s) (1, 10, 1029) (6.0 MB)

ONNX: starting export with onnx 1.21.0 opset 17...
ONNX: slimming with onnxslim 0.1.92...